In [7]:
import pandas as pd

In [8]:
asn = pd.read_csv(
    # "data/IP/ip2asn-v4-u32.tsv.gz",
    "../data/IP/ip2asn-combined.tsv.gz",
    sep="\t",
    header=None,
    names=["range_start", "range_end", "asn", "country_code", "description"],
    keep_default_na=False,
)

print(asn[asn["country_code"] == "GB"].head(10).to_string(index=False))
print(f"{len(asn):,} IP ranges")

range_start   range_end    asn country_code                                                description
   2.26.0.0  2.26.3.255 215439           GB                                                PLAY2GO-NET
   2.26.4.0  2.26.6.255 203154           GB                                         MITELIS-DOWNSTREAM
   2.26.7.0  2.26.7.255 215439           GB                                                PLAY2GO-NET
   2.26.8.0 2.26.11.255 207957           GB                                                SERVHOST-AS
  2.26.16.0 2.26.17.255 206134           GB                                                NEKOBYTE-AS
  2.26.18.0 2.26.19.255 216127           GB                                               AS-NUXTCLOUD
  2.26.20.0 2.26.23.255 215590           GB                                                DPKGSOFT-AS
  2.26.28.0 2.26.30.255 206134           GB                                                NEKOBYTE-AS
  2.26.31.0 2.26.31.255 216127           GB                                               AS-NUXTCLOUD
  2.26.36.0 2.26.39.255  42831           GB UKSERVERS-AS UK Dedicated Servers, Hosting and Co-Location
723,585 IP ranges

In [9]:
categories = pd.read_csv("../data/IP/2026-03_categorized_ases.csv")
print(categories.columns.tolist())
print(categories.head().to_string(index=False))

['ASN', 'Category 1 - Layer 1', 'Category 1 - Layer 2', 'Category 2 - Layer 1', 'Category 2 - Layer 2', 'Category 3 - Layer 1', 'Category 3 - Layer 2', 'Category 4 - Layer 1', 'Category 4 - Layer 2', 'Category 5 - Layer 1', 'Category 5 - Layer 2', 'Category 6 - Layer 1', 'Category 6 - Layer 2', 'Category 7 - Layer 1', 'Category 7 - Layer 2', 'Category 8 - Layer 1', 'Category 8 - Layer 2', 'Category 9 - Layer 1', 'Category 9 - Layer 2', 'Category 10 - Layer 1', 'Category 10 - Layer 2', 'Category 11 - Layer 1', 'Category 11 - Layer 2', 'Category 12 - Layer 1', 'Category 12 - Layer 2', 'Category 13 - Layer 1', 'Category 13 - Layer 2', 'Category 14 - Layer 1', 'Category 14 - Layer 2', 'Category 15 - Layer 1', 'Category 15 - Layer 2', 'Category 16 - Layer 1', 'Category 16 - Layer 2', 'Category 17 - Layer 1', 'Category 17 - Layer 2', 'Category 18 - Layer 1', 'Category 18 - Layer 2', 'Category 19 - Layer 1', 'Category 19 - Layer 2', 'Category 20 - Layer 1', 'Category 20 - Layer 2', 'Category 21 - Layer 1', 'Category 21 - Layer 2', 'Category 22 - Layer 1', 'Category 22 - Layer 2', 'Category 23 - Layer 1', 'Category 23 - Layer 2', 'Category 24 - Layer 1', 'Category 24 - Layer 2', 'Category 25 - Layer 1', 'Category 25 - Layer 2', 'Category 26 - Layer 1', 'Category 26 - Layer 2', 'Category 27 - Layer 1', 'Category 27 - Layer 2', 'Category 28 - Layer 1', 'Category 28 - Layer 2', 'Category 29 - Layer 1', 'Category 29 - Layer 2', 'Category 30 - Layer 1', 'Category 30 - Layer 2', 'Category 31 - Layer 1', 'Category 31 - Layer 2', 'Category 32 - Layer 1', 'Category 32 - Layer 2', 'Category 33 - Layer 1', 'Category 33 - Layer 2', 'Category 34 - Layer 1', 'Category 34 - Layer 2', 'Category 35 - Layer 1', 'Category 35 - Layer 2', 'Category 36 - Layer 1', 'Category 36 - Layer 2', 'Category 37 - Layer 1', 'Category 37 - Layer 2', 'Category 38 - Layer 1', 'Category 38 - Layer 2', 'Category 39 - Layer 1', 'Category 39 - Layer 2', 'Category 40 - Layer 1', 'Category 40 - Layer 2', 'Category 41 - Layer 1', 'Category 41 - Layer 2', 'Category 42 - Layer 1', 'Category 42 - Layer 2', 'Category 43 - Layer 1', 'Category 43 - Layer 2', 'Category 44 - Layer 1', 'Category 44 - Layer 2', 'Category 45 - Layer 1', 'Category 45 - Layer 2', 'Category 46 - Layer 1', 'Category 46 - Layer 2', 'Category 47 - Layer 1', 'Category 47 - Layer 2', 'Category 48 - Layer 1', 'Category 48 - Layer 2', 'Category 49 - Layer 1', 'Category 49 - Layer 2', 'Category 50 - Layer 1', 'Category 50 - Layer 2', 'Category 51 - Layer 1', 'Category 51 - Layer 2', 'Category 52 - Layer 1', 'Category 52 - Layer 2', 'Category 53 - Layer 1', 'Category 53 - Layer 2', 'Category 54 - Layer 1', 'Category 54 - Layer 2', 'Category 55 - Layer 1', 'Category 55 - Layer 2', 'Category 56 - Layer 1', 'Category 56 - Layer 2', 'Category 57 - Layer 1', 'Category 57 - Layer 2', 'Category 58 - Layer 1', 'Category 58 - Layer 2', 'Category 59 - Layer 1', 'Category 59 - Layer 2', 'Category 60 - Layer 1', 'Category 60 - Layer 2', 'Category 61 - Layer 1', 'Category 61 - Layer 2', 'Category 62 - Layer 1', 'Category 62 - Layer 2', 'Category 63 - Layer 1', 'Category 63 - Layer 2', 'Category 64 - Layer 1', 'Category 64 - Layer 2', 'Category 65 - Layer 1', 'Category 65 - Layer 2', 'Category 66 - Layer 1', 'Category 66 - Layer 2', 'Category 67 - Layer 1', 'Category 67 - Layer 2', 'Category 68 - Layer 1', 'Category 68 - Layer 2']
    ASN                           Category 1 - Layer 1                                              Category 1 - Layer 2                           Category 2 - Layer 1            Category 2 - Layer 2                Category 3 - Layer 1                  Category 3 - Layer 2                Category 4 - Layer 1                                              Category 4 - Layer 2                Category 5 - Layer 1            Category 5 - Layer 2 Category 6 - Layer 1 Category 6 - Layer 2 Category 7 - Layer 1 Category 7 - Layer 2 Category 8 - Layer 1 Category 8 - Layer 2 Category 9 - Layer 1 Category 9 - Layer 2 Category 10 - Layer 1 Category 10 - Layer 2 Category 11 - Layer 1 Category 11 - Layer 2 Category 12 - Layer 1 Category 12 - Layer 2 Category 13 - Layer 1 Category 13 - Layer 2 Category 14 - Layer 1 Category 14 - Layer 2 Category 15 - Layer 1 Category 15 - Layer 2 Category 16 - Layer 1 Category 16 - Layer 2 Category 17 - Layer 1 Category 17 - Layer 2 Category 18 - Layer 1 Category 18 - Layer 2 Category 19 - Layer 1 Category 19 - Layer 2 Category 20 - Layer 1 Category 20 - Layer 2 Category 21 - Layer 1 Category 21 - Layer 2 Category 22 - Layer 1 Category 22 - Layer 2 Category 23 - Layer 1 Category 23 - Layer 2 Category 24 - Layer 1 Category 24 - Layer 2 Category 25 - Layer 1 Category 25 - Layer 2 Category 26 - Layer 1 Category 26 - Layer 2 Category 27 - Layer 1 Category 27 - Layer 2 Category 28 - Layer 1 Category 28 - Layer 2 Category 29 - Layer 1 Category 29 - Layer 2 Category 30 - Layer 1 Category 30 - Layer 2 Category 31 - Layer 1 Category 31 - Layer 2 Category 32 - Layer 1 Category 32 - Layer 2 Category 33 - Layer 1 Category 33 - Layer 2 Category 34 - Layer 1 Category 34 - Layer 2  Category 35 - Layer 1  Category 35 - Layer 2  Category 36 - Layer 1  Category 36 - Layer 2  Category 37 - Layer 1  Category 37 - Layer 2  Category 38 - Layer 1  Category 38 - Layer 2  Category 39 - Layer 1  Category 39 - Layer 2  Category 40 - Layer 1  Category 40 - Layer 2  Category 41 - Layer 1  Category 41 - Layer 2  Category 42 - Layer 1  Category 42 - Layer 2  Category 43 - Layer 1  Category 43 - Layer 2  Category 44 - Layer 1  Category 44 - Layer 2  Category 45 - Layer 1  Category 45 - Layer 2  Category 46 - Layer 1  Category 46 - Layer 2  Category 47 - Layer 1  Category 47 - Layer 2  Category 48 - Layer 1  Category 48 - Layer 2  Category 49 - Layer 1  Category 49 - Layer 2  Category 50 - Layer 1  Category 50 - Layer 2  Category 51 - Layer 1  Category 51 - Layer 2  Category 52 - Layer 1  Category 52 - Layer 2  Category 53 - Layer 1  Category 53 - Layer 2  Category 54 - Layer 1  Category 54 - Layer 2  Category 55 - Layer 1  Category 55 - Layer 2  Category 56 - Layer 1  Category 56 - Layer 2  Category 57 - Layer 1  Category 57 - Layer 2  Category 58 - Layer 1  Category 58 - Layer 2  Category 59 - Layer 1  Category 59 - Layer 2  Category 60 - Layer 1  Category 60 - Layer 2  Category 61 - Layer 1  Category 61 - Layer 2  Category 62 - Layer 1  Category 62 - Layer 2  Category 63 - Layer 1  Category 63 - Layer 2  Category 64 - Layer 1  Category 64 - Layer 2  Category 65 - Layer 1  Category 65 - Layer 2  Category 66 - Layer 1  Category 66 - Layer 2  Category 67 - Layer 1  Category 67 - Layer 2  Category 68 - Layer 1  Category 68 - Layer 2
 AS3255            Computer and Information Technology                                   Internet Service Provider (ISP)                                            NaN                             NaN                                 NaN                                   NaN                                 NaN                                                               NaN                                 NaN                             NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN
 AS6837            Computer and Information Technology                                        Hosting and Cloud Provider Retail Stores, Wholesale, and E-commerce Sites                             NaN Computer and Information Technology                                   NaN Computer and Information Technology                                   Internet Service Provider (ISP)                                 NaN                             NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN
AS15756 Retail Stores, Wholesale, and E-commerce Sites                                                             Other            Computer and Information Technology Internet Service Provider (ISP)        Construction and Real Estate Buildings (Residential or Commercial)                                 NaN                                                               NaN                                 NaN                             NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN
AS16054                   Construction and Real Estate Civil Engineering Construction (Utility Lines, Roads and Bridges)            Computer and Information Technology                  Phone Provider Computer and Information Technology                                   NaN        Construction and Real Estate                             Buildings (Residential or Commercial) Computer and Information Technology Internet Service Provider (ISP)                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN

/tmp/ipykernel_2265283/2837093933.py:1: DtypeWarning: Columns (13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68) have mixed types. Specify dtype option on import or set low_memory=False.
  categories = pd.read_csv("../data/IP/2026-03_categorized_ases.csv")

In [10]:
categories["ASN"].str[:3].unique()

array(['AS3', 'AS6', 'AS1', 'AS9', 'AS8', 'AS2', 'AS5', 'AS7', 'AS4',
       'AS0'], dtype=object)

In [11]:
categories["asn"] = categories["ASN"].str.replace("AS", "").astype(int)
asn = asn.merge(categories, how="left", left_on="asn", right_on="asn")

In [12]:
asn[asn["country_code"] == "GB"].head(10)

,range_start,range_end,asn,country_code,description,ASN,Category 1 - Layer 1,Category 1 - Layer 2,Category 2 - Layer 1,Category 2 - Layer 2,...,Category 64 - Layer 1,Category 64 - Layer 2,Category 65 - Layer 1,Category 65 - Layer 2,Category 66 - Layer 1,Category 66 - Layer 2,Category 67 - Layer 1,Category 67 - Layer 2,Category 68 - Layer 1,Category 68 - Layer 2
1264,2.26.0.0,2.26.3.255,215439,GB,PLAY2GO-NET,AS215439,Computer and Information Technology,Computer and Network Security,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1265,2.26.4.0,2.26.6.255,203154,GB,MITELIS-DOWNSTREAM,AS203154,Community Groups and Nonprofits,Other,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1266,2.26.7.0,2.26.7.255,215439,GB,PLAY2GO-NET,AS215439,Computer and Information Technology,Computer and Network Security,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1267,2.26.8.0,2.26.11.255,207957,GB,SERVHOST-AS,AS207957,Manufacturing,Electronics and Computer Components,Computer and Information Technology,"Hosting, Cloud Provider, Data Center, Server C...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1271,2.26.16.0,2.26.17.255,206134,GB,NEKOBYTE-AS,AS206134,Computer and Information Technology,Hosting and Cloud Provider,Computer and Information Technology,Software Development,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1272,2.26.18.0,2.26.19.255,216127,GB,AS-NUXTCLOUD,AS216127,Computer and Information Technology,Internet Service Provider (ISP),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1273,2.26.20.0,2.26.23.255,215590,GB,DPKGSOFT-AS,AS215590,Computer and Information Technology,Internet Service Provider (ISP),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1275,2.26.28.0,2.26.30.255,206134,GB,NEKOBYTE-AS,AS206134,Computer and Information Technology,Hosting and Cloud Provider,Computer and Information Technology,Software Development,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1276,2.26.31.0,2.26.31.255,216127,GB,AS-NUXTCLOUD,AS216127,Computer and Information Technology,Internet Service Provider (ISP),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1278,2.26.36.0,2.26.39.255,42831,GB,"UKSERVERS-AS UK Dedicated Servers, Hosting and...",AS42831,Computer and Information Technology,Hosting and Cloud Provider,Computer and Information Technology,Internet Service Provider (ISP),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
from pathlib import Path
import requests


response = requests.get(
    "https://www.peeringdb.com/api/net",
    params={"depth": 0},
    headers={"Accept": "application/json"},
    timeout=120,
)
response.raise_for_status()

peering = pd.DataFrame(response.json()["data"])
peering = peering.loc[peering["status"].eq("ok")].copy()

columns = [
    "asn", "name", "info_types",
    "website", "info_scope", "updated",
]
peering = peering[columns]

# Inspect the networks from your earlier sample
sample_asns = [215439, 203154, 207957, 206134, 216127, 215590, 42831]
print(peering.loc[peering["asn"].isin(sample_asns)].to_string(index=False))
print(f"\n{len(peering):,} network records")

Path("peeringdb-net.json").write_bytes(response.content)

/home/tsispace/miniconda3/envs/env1/lib/python3.14/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

   asn                           name                              info_types                   website info_scope              updated
216127                      NUXTCLOUD                               [Content]       https://nuxt.cloud/     Europe 2025-11-14T23:26:23Z
215590 DpkgSoft International Limited          [Enterprise, Network Services]      https://xorek.cloud/     Europe 2024-02-24T10:19:45Z
215439                        PLAY2GO                            [Enterprise]     https://play2go.cloud     Europe 2026-10-12T17:36:17Z
207957                SERV.HOST GROUP     [Enterprise, NSP, Network Services]        https://serv.host/     Europe 2026-09-18T19:15:43Z
203154             MITELIS-DOWNSTREAM                               [Content]       https://mitelis.net     Europe 2026-08-25T21:05:32Z
 42831           UK Dedicated Servers [Content, Enterprise, Network Services] https://www.ukservers.com     Global 2026-08-18T11:54:18Z

35,735 network records

41385351

In [14]:
import json
import pandas as pd
from pathlib import Path

payload = json.loads(Path("peeringdb-net.json").read_text())
peering = pd.DataFrame(payload["data"])

In [15]:
peering.sample(10)

,id,org_id,name,aka,name_long,website,social_media,asn,looking_glass,route_server,...,allow_ixp_update,ixp_update_exclude,status_dashboard,rir_status,rir_status_updated,logo,meta,created,updated,status
19249,33288,35488,TVIN-INET,,,,[],197035,,,...,False,[],,ok,2024-06-26T04:47:55Z,None,{},2023-06-02T11:19:28Z,2023-06-02T13:51:44Z,ok
25556,42080,43830,Brander Group Inc.,,,http://brandergroup.net,"[{'service': 'website', 'identifier': 'http://...",210398,,,...,False,[],,ok,2026-04-09T22:55:15Z,None,{},2026-04-09T02:24:27Z,2026-04-09T17:57:16Z,ok
28734,12799,16408,Frontier Optical Networks,FON,Frontier Optical Networks,https://www.fon.co.ke,"[{'service': 'website', 'identifier': 'https:/...",37305,,,...,True,[],,ok,2024-06-26T04:47:55Z,None,{},2017-03-10T10:36:36Z,2026-09-29T08:25:28Z,ok
25224,41698,43439,MONIEPOINT MICROFINANCE BANK LIMITED,,,https://www.moniepoint.com,[],329685,,,...,False,[],None,ok,2026-02-23T22:55:11Z,None,{},2026-02-23T10:13:24Z,2026-02-23T20:16:25Z,ok
582,1338,6070,Clarksys AS7012,,,https://www.clarksys.com,[],7012,,,...,False,[],None,ok,2024-06-26T04:47:55Z,None,{},2007-10-09T17:29:48Z,2022-07-27T05:33:26Z,ok
11185,20488,23003,TELEFÔNICA BRASIL AS22092,Vivo,,http://www.telefonica.com.br,"[{'service': 'website', 'identifier': 'http://...",22092,,,...,False,[],None,ok,2024-06-26T04:47:55Z,None,{},2019-07-30T21:33:19Z,2022-07-27T05:33:48Z,ok
8792,16565,19777,R N DE CASTRO PROVEDOR DE INTERNET,R N DE CASTRO,,http://www.cianet.net.br,"[{'service': 'website', 'identifier': 'http://...",265999,,,...,False,[],None,ok,2024-06-26T04:47:55Z,None,{},2018-04-26T16:26:51Z,2022-07-27T05:36:37Z,ok
31818,25122,27811,BPS COMMUNICATION AND SERVICES,,,,[],133980,,,...,True,[],None,ok,2024-06-26T04:47:55Z,None,{},2020-11-10T06:35:28Z,2022-10-26T05:17:40Z,ok
30983,21756,24667,Tunas Link Indonesia,TINKNET,PT TUNAS LINK INDONESIA,https://tink.net.id,"[{'service': 'facebook', 'identifier': 'tunasl...",138134,,,...,True,[],,ok,2024-06-26T04:47:55Z,None,{},2019-12-12T13:27:24Z,2026-09-16T03:10:28Z,ok
8499,16095,19332,TVB New Media Group Limited,MyTV Super,,http://www.mytvsuper.com,"[{'service': 'website', 'identifier': 'http://...",9253,,,...,False,[],None,ok,2024-06-26T04:47:55Z,None,{},2018-03-12T08:40:34Z,2022-07-27T05:33:30Z,ok

In [16]:
privacy = pd.read_csv(
    "https://ipinfo.io/data/sample/ipinfo_privacy.csv"
)
print(privacy.head(20).to_string(index=False))
print(privacy.dtypes)

      network  hosting  proxy   tor  relay   vpn service
   1.0.0.0/31     True  False False  False False     NaN
      1.0.0.2     True  False False  False  True     NaN
      1.0.0.3     True  False False  False False     NaN
   1.0.0.4/30     True  False False  False False     NaN
   1.0.0.8/29     True  False False  False False     NaN
  1.0.0.16/28     True  False False  False False     NaN
  1.0.0.32/27     True  False False  False False     NaN
  1.0.0.64/26     True  False False  False False     NaN
 1.0.0.128/25     True  False False  False False     NaN
    1.0.7.231    False  False False  False  True     NaN
 1.0.7.242/31    False  False False  False  True     NaN
 1.0.7.244/31    False  False False  False  True     NaN
    1.0.64.29    False  False False  False  True     NaN
     1.0.65.6    False  False False  False  True     NaN
    1.0.65.80    False  False False  False  True     NaN
1.0.66.230/31    False  False False  False  True     NaN
   1.0.67.165    False  False False  False  True     NaN
   1.0.69.106    False  False False  False  True     NaN
   1.0.69.247    False  False False  False  True     NaN
    1.0.70.83    False  False False  False  True     NaN
network    object
hosting      bool
proxy        bool
tor          bool
relay        bool
vpn          bool
service    object
dtype: object

In [17]:
lite = pd.read_parquet("../data/IP/ipinfo_lite.parquet")
print(lite.head(10).to_string(index=False))

    network   country country_code continent continent_code     asn                      as_name       as_domain
 1.0.0.0/24 Australia           AU   Oceania             OC AS13335             Cloudflare, Inc.  cloudflare.com
 1.0.1.0/24     China           CN      Asia             AS    None                         None            None
 1.0.2.0/23     China           CN      Asia             AS    None                         None            None
 1.0.4.0/22 Australia           AU   Oceania             OC AS38803             Gtelecom Pty Ltd gtelecom.com.au
 1.0.8.0/21     China           CN      Asia             AS    None                         None            None
1.0.16.0/24     Japan           JP      Asia             AS  AS2519 ARTERIA Networks Corporation arteria-net.com
1.0.17.0/24     Japan           JP      Asia             AS    None                         None            None
1.0.18.0/23     Japan           JP      Asia             AS    None                         None            None
1.0.20.0/22     Japan           JP      Asia             AS    None                         None            None
1.0.24.0/21     Japan           JP      Asia             AS    None                         None            None

In [18]:
import requests

from ipaddress import ip_address

response = requests.get(
    "https://check.torproject.org/torbulkexitlist",
    timeout=60,
)
response.raise_for_status()

tor_ips = {
    str(ip_address(line.strip()))
    for line in response.text.splitlines()
    if line.strip() and not line.lstrip().startswith("#")
}

tor = pd.DataFrame({"ip": sorted(tor_ips)})
print(tor.head(10).to_string(index=False))
print(f"{len(tor):,} distinct Tor exit IPs")

             ip
  102.130.113.9
102.130.117.167
102.130.127.117
  102.211.56.20
102.223.198.101
   102.68.99.63
103.109.101.105
 103.109.187.71
103.146.203.120
 103.146.203.14
1,214 distinct Tor exit IPs

In [19]:
from pathlib import Path
from urllib.request import urlretrieve
from ipaddress import ip_network

sources = {
    "vpn": "https://raw.githubusercontent.com/X4BNet/lists_vpn/main/output/vpn/ipv4.txt",
    "datacenter": "https://raw.githubusercontent.com/X4BNet/lists_vpn/main/output/datacenter/ipv4.txt",
}

for name, url in sources.items():
    subnet_file = Path(f"/tmp/{name}_subnets.txt")
    ip_file = Path(f"/tmp/{name}_ips.txt")

    urlretrieve(url, subnet_file)

    count = 0
    with subnet_file.open() as subnets, ip_file.open("w") as ips:
        for line in subnets:
            subnet = line.strip()
            if not subnet:
                continue

            network = ip_network(subnet, strict=False)
            for address in network:
                ips.write(f"{address}\n")
                count += 1

    print(f"{name}: wrote {count:,} IP addresses to {ip_file}")

vpn: wrote 3,170,072 IP addresses to /tmp/vpn_ips.txt

KeyboardInterrupt:

In [20]:
import urllib.request, hashlib, datetime
from pathlib import Path
from ipaddress import ip_network, ip_address
import numpy as np

RAW = Path("data/raw/x4bnet") / datetime.date.today().isoformat()
RAW.mkdir(parents=True, exist_ok=True)
URL = "https://raw.githubusercontent.com/X4BNet/lists_vpn/main/output/{}/ipv4.txt"

def fetch(name):
    data = urllib.request.urlopen(URL.format(name), timeout=60).read()
    (RAW / f"{name}_ipv4.txt").write_bytes(data)
    return hashlib.sha256(data).hexdigest()

def load_intervals(path):
    nets = sorted(ip_network(l.strip(), strict=False)
                  for l in path.read_text().splitlines() if l.strip())
    s = np.array([int(n.network_address) for n in nets], dtype=np.uint64)
    e = np.array([int(n.broadcast_address) for n in nets], dtype=np.uint64)
    assert (s[1:] > e[:-1]).all(), "overlapping ranges: collapse first"
    return s, e

def in_list(ips_u32, s, e):
    i = np.searchsorted(s, ips_u32, side="right") - 1
    out = np.zeros(len(ips_u32), bool)
    ok = i >= 0
    out[ok] = ips_u32[ok] <= e[i[ok]]
    return out

In [21]:
import numpy as np, pandas as pd
from ipaddress import ip_address

def ip_to_u32(x):
    try:
        a = ip_address(x)
    except ValueError:
        return -1
    if a.version == 6:
        a = a.ipv4_mapped      # None for real IPv6
        if a is None:
            return -1
    return int(a)

def flag_ips(ip_series, s, e):
    uniq = pd.Series(ip_series.dropna().unique())   # look up each IP once
    codes = uniq.map(ip_to_u32).to_numpy(dtype=np.int64)
    flags = np.zeros(len(uniq), bool)
    ok = codes >= 0
    flags[ok] = in_list(codes[ok].astype(np.uint64), s, e)
    return ip_series.map(dict(zip(uniq, flags))).fillna(False).astype(bool)

In [ ]:
hashes = {n: fetch(n) for n in ("vpn", "datacenter")}          # 1. download, record hashes
iv = {n: load_intervals(RAW / f"{n}_ipv4.txt") for n in hashes}  # 2. build interval arrays

for n, (s, e) in iv.items():                                    # 3. flag your dataframe
    df[f"is_{n}"] = flag_ips(df["ip"], s, e)

NameError: name 'df' is not defined

In [ ]:
%%bash

# All AWS IPs (plain text)
curl -sL https://raw.githubusercontent.com/rezmoss/cloud-provider-ip-addresses/main/aws/aws_ips.txt

# Cloudflare IPv4 only
curl -sL https://raw.githubusercontent.com/rezmoss/cloud-provider-ip-addresses/main/cloudflare/cloudflare_ips_v4.txt

# All providers merged into one optimized IPv4 list
curl -sL https://raw.githubusercontent.com/rezmoss/cloud-provider-ip-addresses/main/all_providers/all_providers_merged_v4.txt

# Block GPTBot with iptables
curl -sL https://raw.githubusercontent.com/rezmoss/cloud-provider-ip-addresses/main/gptbot/iptables_gptbot_deny.sh | sudo bash

# AWS Nginx allow config — drop into your server block
curl -sL https://raw.githubusercontent.com/rezmoss/cloud-provider-ip-addresses/main/aws/nginx_aws_allow.conf -o /etc/nginx/conf.d/aws_allow.conf

# Unified dataset (all providers, normalized JSON)
curl -sL https://raw.githubusercontent.com/rezmoss/cloud-provider-ip-addresses/main/all_providers/all_providers.json

# Look up an IP
curl -sL https://raw.githubusercontent.com/rezmoss/cloud-provider-ip-addresses/main/lookup.py -o lookup.py
python3 lookup.py --data-dir . 13.32.0.1

1.178.1.0/24
1.178.1.0/24
1.178.4.0/24
1.178.4.0/24
1.178.4.0/24
1.178.5.0/24
1.178.5.0/24
1.178.5.0/24
1.178.6.0/24
1.178.6.0/24
1.178.6.0/24
1.178.7.0/24
1.178.7.0/24
1.178.7.0/24
1.178.8.0/24
1.178.8.0/24
1.178.8.0/24
1.178.9.0/24
1.178.9.0/24
1.178.9.0/24
1.178.10.0/24
1.178.10.0/24
1.178.10.0/24
1.178.11.0/24
1.178.11.0/24
1.178.11.0/24
1.178.16.0/24
1.178.16.0/24
1.178.16.0/24
1.178.17.0/24
1.178.17.0/24
1.178.17.0/24
1.178.18.0/24
1.178.18.0/24
1.178.18.0/24
1.178.19.0/24
1.178.19.0/24
1.178.19.0/24
1.178.20.0/24
1.178.20.0/24
1.178.20.0/24
1.178.21.0/24
1.178.21.0/24
1.178.21.0/24
1.178.22.0/24
1.178.22.0/24
1.178.22.0/24
1.178.23.0/24
1.178.23.0/24
1.178.23.0/24
1.178.24.0/24
1.178.24.0/24
1.178.24.0/24
1.178.25.0/24
1.178.25.0/24
1.178.25.0/24
1.178.26.0/24
1.178.26.0/24
1.178.26.0/24
1.178.27.0/24
1.178.27.0/24
1.178.27.0/24
1.178.28.0/24
1.178.28.0/24
1.178.28.0/24
1.178.29.0/24
1.178.29.0/24
1.178.29.0/24
1.178.30.0/24
1.178.30.0/24
1.178.30.0/24
1.178.31.0/24
1.178.31.0/24
1.178.31.0/24
1.178.64.0/24
1.178.64.0/24
1.178.64.0/24
1.178.65.0/24
1.178.65.0/24
1.178.65.0/24
1.178.72.0/21
1.178.86.0/24
1.178.86.0/24
1.178.88.0/24
1.178.88.0/24
1.178.88.0/24
1.178.89.0/24
1.178.89.0/24
1.178.89.0/24
1.178.90.0/24
1.178.90.0/24
1.178.90.0/24
1.178.91.0/24
1.178.91.0/24
1.178.91.0/24
1.178.92.0/24
1.178.92.0/24
1.178.92.0/24
1.178.93.0/24
1.178.93.0/24
1.178.93.0/24
1.178.94.0/24
1.178.94.0/24
1.178.94.0/24
1.178.95.0/24
1.178.95.0/24
1.178.95.0/24
1.178.100.0/24
1.178.100.0/24
1.178.100.0/24
1.178.101.0/24
1.178.101.0/24
1.178.101.0/24
1.178.102.0/24
1.178.102.0/24
1.178.102.0/24
1.178.103.0/24
1.178.103.0/24
1.178.103.0/24
1.178.172.0/23
1.178.172.0/23
1.178.174.0/24
1.178.174.0/24
1.179.2.0/23
1.179.14.0/23
1.179.14.0/23
1.179.52.0/22
1.179.52.0/22
1.179.56.0/22
1.179.56.0/22
1.179.60.0/23
1.179.60.0/23
1.179.101.0/24
1.179.101.0/24
1.179.102.0/24
1.179.102.0/24
1.179.103.0/24
1.179.103.0/24
3.0.0.0/15
3.0.0.0/15
3.0.5.32/29
3.0.5.224/27
3.2.0.0/24
3.2.0.0/24
3.2.1.0/24
3.2.2.0/24
3.2.2.0/24
3.2.3.0/24
3.2.3.0/24
3.2.4.0/23
3.2.4.0/23
3.2.8.0/21
3.2.8.0/21
3.2.48.0/24
3.2.48.0/24
3.2.49.0/24
3.2.49.0/24
3.2.50.0/24
3.2.50.0/24
3.2.51.0/24
3.2.51.0/24
3.2.52.0/24
3.2.52.0/24
3.2.53.0/24
3.2.53.0/24
3.2.54.0/24
3.2.54.0/24
3.2.55.0/24
3.2.55.0/24
3.2.56.0/24
3.2.56.0/24
3.2.57.0/24
3.2.57.0/24
3.2.58.0/24
3.2.58.0/24
3.2.59.0/24
3.2.59.0/24
3.2.60.0/24
3.2.60.0/24
3.2.61.0/24
3.2.61.0/24
3.2.64.0/24
3.2.64.0/24
3.2.64.0/24
3.2.65.0/24
3.2.65.0/24
3.2.65.0/24
3.2.66.0/24
3.2.66.0/24
3.2.66.0/24
3.2.67.0/24
3.2.67.0/24
3.2.67.0/24
3.2.68.0/24
3.2.68.0/24
3.2.68.0/24
3.2.69.0/24
3.2.69.0/24
3.2.69.0/24
3.2.70.0/24
3.2.70.0/24
3.2.70.0/24
3.2.71.0/24
3.2.71.0/24
3.2.71.0/24
3.2.72.0/24
3.2.72.0/24
3.2.72.0/24
3.2.73.0/24
3.2.73.0/24
3.2.74.0/24
3.2.74.0/24
3.2.74.0/24
3.2.75.0/24
3.2.75.0/24
3.2.75.0/24
3.2.76.0/24
3.2.76.0/24
3.2.76.0/24
3.2.77.0/24
3.2.77.0/24
3.2.77.0/24
3.2.78.0/24
3.2.78.0/24
3.2.78.0/24
3.2.79.0/24
3.2.79.0/24
3.2.79.0/24
3.2.80.0/24
3.2.80.0/24
3.2.80.0/24
3.2.81.0/24
3.2.81.0/24
3.2.81.0/24
3.2.82.0/24
3.2.82.0/24
3.2.82.0/24
3.2.83.0/24
3.2.83.0/24
3.2.83.0/24
3.2.84.0/24
3.2.84.0/24
3.2.84.0/24
3.2.85.0/24
3.2.85.0/24
3.2.85.0/24
3.2.86.0/24
3.2.86.0/24
3.2.86.0/24
3.2.87.0/24
3.2.87.0/24
3.2.87.0/24
3.2.88.0/24
3.2.88.0/24
3.2.88.0/24
3.2.89.0/24
3.2.89.0/24
3.2.90.0/24
3.2.90.0/24
3.2.90.0/24
3.2.91.0/24
3.2.91.0/24
3.2.91.0/24
3.2.92.0/24
3.2.92.0/24
3.2.92.0/24
3.2.93.0/24
3.2.93.0/24
3.2.93.0/24
3.2.94.0/24
3.2.94.0/24
3.2.94.0/24
3.2.95.0/24
3.2.95.0/24
3.2.95.0/24
3.2.96.0/24
3.2.96.0/24
3.2.96.0/24
3.2.97.0/24
3.2.97.0/24
3.2.97.0/24
3.2.98.0/24
3.2.98.0/24
3.2.98.0/24
3.2.99.0/24
3.2.99.0/24
3.2.99.0/24
3.2.100.0/24
3.2.100.0/24
3.2.100.0/24
3.2.101.0/24
3.2.101.0/24
3.2.101.0/24
3.2.102.0/24
3.2.102.0/24
3.2.102.0/24
3.2.103.0/24
3.2.103.0/24
3.2.103.0/24
3.2.104.0/24
3.2.104.0/24
3.2.104.0/24
3.2.105.0/24
3.2.105.0/24
3.2.105.0/24
3.2.106.0/24
3.2.106.0/24
3.2.106.0/24
3.2.107.0/24
3.2.107.0/24
3.2.107.0/24
3.2.108.0/24
3.2.108.0/24
3.2.108.0/24
3.2.109.0/24
3.2.109.0/24
3.2.109.0/24
3.2.110.0/24
3.2.110.0/24
3.2.110.0/24
3.2.111.0/24
3.2.111.0/24
3.2.111.0/24
3.2.112.0/24
3.2.112.0/24
3.2.112.0/24
3.2.113.0/24
3.2.113.0/24
3.2.113.0/24
3.2.114.0/24
3.2.114.0/24
3.2.114.0/24
3.2.115.0/24
3.2.115.0/24
3.2.115.0/24
3.2.116.0/24
3.2.116.0/24
3.2.116.0/24
3.2.117.0/24
3.2.117.0/24
3.2.117.0/24
3.2.118.0/24
3.2.118.0/24
3.2.118.0/24
3.2.119.0/24
3.2.119.0/24
3.2.119.0/24
3.2.120.0/24
3.2.120.0/24
3.2.120.0/24
3.2.121.0/24
3.2.121.0/24
3.2.121.0/24
3.2.122.0/24
3.2.122.0/24
3.2.122.0/24
3.2.123.0/24
3.2.123.0/24
3.2.123.0/24
3.2.124.0/24
3.2.124.0/24
3.2.124.0/24
3.2.125.0/24
3.2.125.0/24
3.2.125.0/24
3.2.126.0/24
3.2.126.0/24
3.2.126.0/24
3.2.127.0/24
3.2.127.0/24
3.2.127.0/24
3.3.0.0/23
3.3.0.0/23
3.3.2.0/24
3.3.2.0/24
3.3.5.0/24
3.3.5.0/24
3.3.6.0/23
3.3.6.0/23
3.3.8.0/21
3.3.8.0/21
3.3.16.0/21
3.3.24.0/22
3.3.28.0/22
3.3.32.0/23
3.3.32.0/23
3.4.0.0/24
3.4.0.0/24
3.4.1.0/24
3.4.1.0/24
3.4.2.0/24
3.4.2.0/24
3.4.3.0/24
3.4.3.0/24
3.4.4.0/24
3.4.4.0/24
3.4.6.0/24
3.4.6.0/24
3.4.8.0/24
3.4.8.0/24
3.4.9.0/24
3.4.9.0/24
3.4.10.0/24
3.4.10.0/24
3.4.12.1/32
3.4.12.2/32
3.4.12.3/32
3.4.12.4/32
3.4.12.5/32
3.4.12.6/32
3.4.12.11/32
3.4.12.12/32
3.4.12.15/32
3.4.12.16/32
3.4.12.17/32
3.4.12.18/32
3.4.12.19/32
3.4.12.20/32
3.4.12.21/32
3.4.12.22/32
3.4.12.23/32
3.4.12.24/32
3.4.12.25/32
3.4.12.26/32
3.4.12.27/32
3.4.12.28/32
3.4.12.29/32
3.4.12.30/32
3.4.12.31/32
3.4.12.32/32
3.4.12.33/32
3.4.12.34/32
3.4.12.35/32
3.4.12.36/32
3.4.12.37/32
3.4.12.38/32
3.4.12.39/32
3.4.12.40/32
3.4.12.41/32
3.4.12.42/32
3.4.12.43/32
3.4.12.44/32
3.4.12.45/32
3.4.12.46/32
3.4.12.49/32
3.4.12.50/32
3.4.12.51/32
3.4.12.52/32
3.4.12.53/32
3.4.12.54/32
3.4.12.55/32
3.4.12.56/32
3.4.12.57/32
3.4.12.58/32
3.4.12.59/32
3.4.12.60/32
3.4.12.61/32
3.4.12.62/32
3.4.12.63/32
3.4.12.64/32
3.4.12.65/32
3.4.12.66/32
3.4.12.67/32
3.4.12.68/32
3.4.12.69/32
3.4.12.70/32
3.4.12.71/32
3.4.12.72/32
3.4.12.73/32
3.4.12.74/32
3.4.12.75/32
3.4.12.76/32
3.4.12.77/32
3.4.12.78/32
3.4.12.79/32
3.4.12.80/32
3.4.12.81/32
3.4.12.82/32
3.4.12.83/32
3.4.12.84/32
3.4.12.85/32
3.4.12.86/32
3.4.13.0/28
3.4.13.16/28
3.4.13.32/28
3.4.13.48/28
3.4.13.64/28
3.4.13.80/28
3.4.14.0/29
3.4.14.8/29
3.4.14.16/29
3.4.14.24/29
3.4.14.32/29
3.4.15.0/29
3.4.15.8/29
3.4.15.16/29
3.4.15.24/29
3.4.15.32/29
3.4.15.40/29
3.4.15.48/29
3.4.15.56/29
3.4.15.64/29
3.4.15.72/29
3.4.15.80/29
3.4.15.88/29
3.4.15.96/29
3.4.15.104/29
3.4.15.112/29
3.4.15.120/29
3.4.15.128/29
3.4.15.136/29
3.4.15.152/29
3.4.15.160/29
3.4.15.168/29
3.4.15.176/29
3.4.15.184/29
3.4.15.192/29
3.4.15.200/29
3.4.15.208/29
3.4.15.216/29
3.4.15.224/29
3.4.15.232/29
3.4.15.240/29
3.4.15.248/29
3.4.16.0/21
3.4.16.0/21
3.4.24.0/21
3.4.24.0/21
3.4.24.0/23
3.4.26.0/23
3.4.32.0/20
3.4.32.0/20
3.5.0.0/19
3.5.0.0/19
3.5.0.0/19
3.5.32.0/22
3.5.32.0/22
3.5.32.0/22
3.5.36.0/22
3.5.36.0/22
3.5.36.0/22
3.5.40.0/22
3.5.40.0/22
3.5.40.0/22
3.5.44.0/22
3.5.44.0/22
3.5.44.0/22
3.5.48.0/22
3.5.48.0/22
3.5.48.0/22
3.5.52.0/22
3.5.52.0/22
3.5.52.0/22
3.5.56.0/22
3.5.56.0/22
3.5.56.0/22
3.5.60.0/22
3.5.60.0/22
3.5.60.0/22
3.5.64.0/21
3.5.64.0/21
3.5.64.0/21
3.5.72.0/23
3.5.72.0/23
3.5.72.0/23
3.5.74.0/23
3.5.74.0/23
3.5.74.0/23
3.5.76.0/22
3.5.76.0/22
3.5.76.0/22
3.5.80.0/21
3.5.80.0/21
3.5.80.0/21
3.5.88.0/22
3.5.88.0/22
3.5.88.0/22
3.5.92.0/23
3.5.92.0/23
3.5.92.0/23
3.5.94.0/23
3.5.94.0/23
3.5.94.0/23
3.5.96.0/23
3.5.96.0/23
3.5.96.0/23
3.5.98.0/23
3.5.98.0/23
3.5.98.0/23
3.5.100.0/22
3.5.100.0/22
3.5.100.0/22
3.5.104.0/22
3.5.104.0/22
3.5.104.0/22
3.5.108.0/22
3.5.108.0/22
3.5.108.0/22
3.5.120.0/22
3.5.120.0/22
3.5.120.0/22
3.5.126.0/23
3.5.126.0/23
3.5.126.0/23
3.5.128.0/22
3.5.128.0/22
3.5.128.0/22
3.5.132.0/23
3.5.132.0/23
3.5.132.0/23
3.5.134.0/23
3.5.134.0/23
3.5.134.0/23
3.5.136.0/22
3.5.136.0/22
3.5.136.0/22
3.5.140.0/22
3.5.140.0/22
3.5.140.0/22
3.5.144.0/23
3.5.144.0/23
3.5.144.0/23
3.5.146.0/23
3.5.146.0/23
3.5.146.0/23
3.5.148.0/22
3.5.148.0/22
3.5.148.0/22
3.5.152.0/21
3.5.152.0/21
3.5.152.0/21
3.5.160.0/22
3.5.160.0/22
3.5.160.0/22
3.5.164.0/22
3.5.164.0/22
3.5.164.0/22
3.5.168.0/23
3.5.168.0/23
3.5.168.0/23
3.5.172.0/22
3.5.172.0/22
3.5.172.0/22
3.5.180.0/22
3.5.180.0/22
3.5.180.0/22
3.5.184.0/21
3.5.184.0/21
3.5.184.0/21
3.5.192.0/22
3.5.192.0/22
3.5.192.0/22
3.5.196.0/22
3.5.196.0/22
3.5.196.0/22
3.5.202.0/23
3.5.202.0/23
3.5.202.0/23
3.5.204.0/22
3.5.204.0/22
3.5.204.0/22
3.5.208.0/22
3.5.208.0/22
3.5.208.0/22
3.5.212.0/23
3.5.212.0/23
3.5.212.0/23
3.5.214.0/23
3.5.214.0/23
3.5.214.0/23
3.5.216.0/22
3.5.216.0/22
3.5.216.0/22
3.5.220.0/22
3.5.220.0/22
3.5.220.0/22
3.5.224.0/22
3.5.224.0/22
3.5.224.0/22
3.5.228.0/22
3.5.228.0/22
3.5.228.0/22
3.5.232.0/22
3.5.232.0/22
3.5.232.0/22
3.5.236.0/22
3.5.236.0/22
3.5.236.0/22
3.5.240.0/22
3.5.240.0/22
3.5.240.0/22
3.5.244.0/22
3.5.244.0/22
3.5.244.0/22
3.5.248.0/22
3.5.248.0/22
3.5.248.0/22
3.5.252.0/22
3.5.252.0/22
3.5.252.0/22
3.6.0.0/15
3.6.0.0/15
3.6.70.76/30
3.6.70.128/26
3.7.10.0/23
3.7.25.48/30
3.8.0.0/14
3.8.0.0/14
3.8.37.24/29
3.8.37.96/27
3.8.168.0/23
3.9.41.0/27
3.9.41.32/27
3.9.41.64/27
3.9.94.0/24
3.9.159.64/30
3.9.159.68/30
3.9.159.72/30
3.10.17.0/25
3.10.17.128/25
3.10.127.32/27
3.10.201.64/27
3.10.201.128/27
3.10.201.192/26
3.11.53.0/24
3.12.0.0/16
3.12.0.0/16
3.12.23.88/30
3.12.23.92/30
3.12.23.128/26
3.12.216.0/22
3.13.0.0/16
3.13.0.0/16
3.14.0.0/15
3.14.0.0/15
3.15.35.0/24
3.15.36.0/26
3.15.36.64/26
3.16.0.0/14
3.16.0.0/14
3.16.146.0/29
3.17.136.0/23
3.18.132.0/26
3.18.132.64/26
3.19.147.0/25
3.19.147.128/25
3.20.0.0/14
3.20.0.0/14
3.21.86.0/23
3.24.0.0/14
3.24.0.0/14
3.24.1.208/28
3.24.227.192/26
3.25.37.64/26
3.25.37.128/25
3.25.38.0/23
3.25.40.0/24
3.25.43.0/24
3.25.44.0/23
3.25.47.28/30
3.25.47.32/30
3.25.138.0/26
3.25.138.64/26
3.25.178.128/26
3.25.248.0/22
3.26.58.224/27
3.26.81.0/27
3.26.81.32/27
3.26.82.236/30
3.26.82.240/29
3.26.83.0/24
3.26.84.0/23
3.26.86.0/23
3.26.88.0/28
3.26.88.16/28
3.26.109.216/30
3.26.127.24/29
3.26.137.0/24
3.26.138.0/23
3.26.140.64/26
3.26.246.0/23
3.26.248.0/22
3.27.127.176/29
3.27.127.184/29
3.27.176.0/22
3.28.0.0/15
3.28.0.0/15
3.28.63.128/26
3.28.63.192/26
3.28.64.0/24
3.28.65.0/26
3.28.70.48/28
3.28.70.96/28
3.28.70.112/28
3.28.72.0/23
3.28.211.128/25
3.28.229.0/24
3.28.255.80/28
3.28.255.128/25
3.29.3.128/25
3.29.17.0/25
3.29.17.128/25
3.29.40.64/26
3.29.40.128/26
3.29.40.192/26
3.29.57.0/26
3.29.57.0/26
3.29.89.0/24
3.29.147.40/29
3.29.147.48/28
3.29.156.0/22
3.29.160.0/23
3.29.202.240/28
3.30.0.0/15
3.30.0.0/15
3.30.40.84/30
3.30.98.64/26
3.30.98.128/26
3.30.129.0/24
3.30.130.0/23
3.30.204.0/24
3.32.0.0/16
3.32.0.0/16
3.32.43.160/27
3.32.139.0/24
3.32.190.0/25
3.32.190.128/27
3.32.190.160/27
3.32.190.244/30
3.32.190.248/29
3.32.249.128/25
3.33.0.0/24
3.33.1.0/24
3.33.44.0/22
3.33.128.0/17
3.33.128.0/17
3.34.0.0/15
3.34.0.0/15
3.34.37.0/24
3.34.38.0/23
3.34.89.64/26
3.34.89.192/30
3.34.89.196/30
3.34.101.192/26
3.34.228.0/26
3.34.228.64/26
3.35.130.128/25
3.35.160.0/22
3.36.0.0/14
3.36.0.0/14
3.36.3.96/27
3.36.3.160/28
3.36.3.192/27
3.36.3.224/27
3.36.167.28/30
3.36.167.48/29
3.36.167.64/28
3.36.167.80/28
3.36.167.128/25
3.36.190.0/23
3.36.192.0/23
3.36.194.0/23
3.36.202.0/25
3.36.245.204/30
3.36.245.232/30
3.38.90.8/29
3.38.131.192/26
3.38.229.0/25
3.38.248.0/23
3.39.82.128/25
3.39.113.0/24
3.39.114.0/23
3.39.116.0/26
3.40.0.0/17
3.40.0.0/17
3.40.128.0/17
3.40.128.0/17
3.41.0.0/17
3.41.0.0/17
3.41.128.0/17
3.41.128.0/17
3.41.208.0/25
3.42.0.0/17
3.42.0.0/17
3.42.128.0/17
3.42.128.0/17
3.43.0.0/18
3.43.0.0/18
3.43.64.0/18
3.43.64.0/18
3.43.128.0/18
3.43.128.0/18
3.43.192.0/18
3.43.192.0/18
3.44.0.0/18
3.44.0.0/18
3.44.5.128/25
3.44.64.0/18
3.44.64.0/18
3.44.64.128/25
3.44.128.0/18
3.44.128.0/18
3.44.192.0/18
3.44.192.0/18
3.44.193.128/25
3.45.0.0/18
3.45.0.0/18
3.45.64.0/18
3.45.64.0/18
3.64.0.0/12
3.64.0.0/12
3.64.1.0/26
3.64.1.64/26
3.64.1.128/26
3.64.1.192/29
3.64.1.200/29
3.64.226.232/29
3.64.226.240/30
3.65.124.0/22
3.65.128.0/22
3.65.132.0/22
3.65.246.0/28
3.65.246.16/28
3.66.172.0/24
3.68.251.176/30
3.68.251.232/29
3.70.195.64/26
3.70.195.128/25
3.70.211.0/25
3.70.212.128/26
3.71.104.0/24
3.71.120.0/22
3.72.33.128/25
3.72.168.0/24
3.74.148.128/26
3.75.112.0/24
3.77.79.224/29
3.77.79.232/29
3.78.202.0/23
3.78.204.0/22
3.80.0.0/12
3.80.0.0/12
3.80.16.0/23
3.83.168.0/22
3.91.171.128/25
3.96.0.0/15
3.96.0.0/15
3.96.2.68/30
3.96.2.72/30
3.96.84.0/26
3.96.143.128/26
3.96.143.192/26
3.97.20.0/22
3.97.49.128/25
3.97.99.64/28
3.97.99.96/27
3.97.99.128/27
3.97.99.160/27
3.97.192.112/29
3.97.192.128/25
3.97.217.0/24
3.97.218.0/24
3.97.219.0/24
3.97.230.0/25
3.98.0.0/15
3.98.0.0/15
3.98.24.0/28
3.98.24.16/28
3.98.86.0/23
3.98.171.92/30
3.98.171.196/30
3.98.171.224/29
3.99.124.0/26
3.99.194.0/23
3.99.196.0/22
3.101.0.0/16
3.101.0.0/16
3.101.52.208/30
3.101.52.212/30
3.101.87.0/26
3.101.100.128/25
3.101.114.0/26
3.101.114.64/26
3.101.145.192/27
3.101.145.224/27
3.101.156.0/26
3.101.157.128/25
3.101.158.0/23
3.101.160.44/30
3.101.160.48/28
3.101.160.240/29
3.101.161.0/25
3.101.161.128/25
3.101.162.0/24
3.101.163.0/26
3.101.163.64/28
3.101.163.80/28
3.101.163.96/28
3.101.164.0/24
3.101.176.0/24
3.101.177.20/30
3.101.177.48/29
3.101.194.128/26
3.101.200.0/24
3.101.201.128/25
3.101.202.0/23
3.101.208.0/24
3.101.209.0/26
3.101.226.80/29
3.101.226.88/29
3.101.232.0/22
3.101.239.34/31
3.101.239.36/30
3.102.0.0/15
3.102.0.0/15
3.102.38.0/24
3.102.47.0/24
3.102.48.0/24
3.102.49.0/24
3.102.50.0/23
3.102.52.0/24
3.102.59.0/24
3.102.88.0/24
3.102.119.96/28
3.102.119.112/28
3.103.24.192/28
3.103.24.208/29
3.103.60.0/24
3.103.82.0/24
3.103.138.0/23
3.103.180.128/25
3.103.244.0/22
3.103.254.0/23
3.104.0.0/14
3.104.0.0/14
3.104.82.0/23
3.105.5.0/27
3.105.5.32/27
3.105.172.0/22
3.107.11.160/31
3.107.11.164/30
3.107.30.180/31
3.107.30.184/30
3.107.43.128/25
3.107.44.0/25
3.107.44.128/25
3.107.82.24/29
3.108.0.0/14
3.108.0.0/14
3.108.13.124/30
3.109.72.0/25
3.109.72.152/29
3.110.57.0/24
3.110.71.0/26
3.111.90.0/23
3.111.110.0/23
3.111.251.0/24
3.112.0.0/14
3.112.0.0/14
3.112.23.0/29
3.112.64.0/23
3.112.85.96/27
3.112.96.0/26
3.112.96.64/26
3.112.96.128/27
3.112.96.160/27
3.112.162.0/23
3.113.218.0/26
3.113.218.68/30
3.113.218.72/30
3.113.218.76/30
3.113.218.112/28
3.113.218.128/27
3.114.164.0/22
3.120.0.0/14
3.120.0.0/14
3.120.181.40/29
3.120.181.224/27
3.122.128.0/23
3.123.12.192/26
3.123.14.0/24
3.123.15.0/25
3.123.44.0/27
3.123.44.80/28
3.123.44.96/27
3.123.44.128/27
3.123.44.160/27
3.124.0.0/14
3.124.0.0/14
3.127.48.128/26
3.127.48.244/30
3.127.48.248/30
3.127.74.0/23
3.128.0.0/15
3.128.0.0/15
3.128.56.64/26
3.128.56.128/26
3.128.56.192/26
3.128.93.0/24
3.130.0.0/16
3.130.0.0/16
3.131.0.0/16
3.131.0.0/16
3.132.0.0/14
3.132.0.0/14
3.134.215.0/24
3.136.0.0/13
3.136.0.0/13
3.139.136.128/27
3.139.136.184/30
3.139.136.192/26
3.140.136.128/27
3.141.102.184/29
3.141.102.192/30
3.141.102.208/28
3.141.102.224/28
3.141.252.0/22
3.142.0.0/22
3.142.4.0/22
3.143.206.104/29
3.144.0.0/13
3.144.0.0/13
3.144.141.192/26
3.145.31.0/26
3.145.31.128/26
3.145.220.0/22
3.145.230.0/24
3.145.232.192/26
3.145.242.0/24
3.145.246.48/29
3.145.246.56/29
3.146.8.0/22
3.146.12.0/22
3.146.22.0/26
3.146.29.66/31
3.146.36.192/26
3.146.42.64/30
3.146.42.74/31
3.146.42.80/30
3.146.43.0/25
3.146.44.0/23
3.146.72.40/29
3.146.84.0/22
3.146.232.0/22
3.147.164.0/22
3.147.244.0/22
3.148.161.192/26
3.149.13.208/29
3.149.210.128/26
3.151.45.0/24
3.160.0.0/14
3.160.0.0/14
3.164.0.0/18
3.164.0.0/18
3.164.64.0/18
3.164.64.0/18
3.164.128.0/17
3.164.128.0/17
3.165.0.0/16
3.165.0.0/16
3.166.0.0/15
3.166.0.0/15
3.168.0.0/14
3.168.0.0/14
3.172.0.0/18
3.172.0.0/18
3.172.0.0/18
3.172.64.0/18
3.172.64.0/18
3.172.64.0/18
3.173.0.0/17
3.173.0.0/17
3.173.128.0/18
3.173.128.0/18
3.173.192.0/18
3.173.192.0/18
3.174.0.0/15
3.174.0.0/15
3.208.0.0/12
3.208.0.0/12
3.208.72.176/28
3.209.83.0/27
3.209.83.32/27
3.209.83.64/27
3.209.83.96/27
3.209.83.144/28
3.209.83.160/27
3.209.83.192/26
3.209.84.0/25
3.209.84.128/25
3.209.85.0/25
3.209.85.128/27
3.209.85.160/27
3.209.85.192/27
3.209.87.0/25
3.209.87.128/25
3.209.202.48/28
3.216.99.160/27
3.216.135.0/24
3.216.136.0/21
3.216.144.0/23
3.216.148.0/22
3.217.228.0/22
3.218.180.0/22
3.224.0.0/12
3.224.0.0/12
3.227.4.0/22
3.227.250.128/25
3.228.170.0/26
3.228.170.64/26
3.228.170.128/25
3.228.171.0/25
3.228.171.128/25
3.228.172.0/25
3.228.172.128/25
3.228.173.0/25
3.228.173.128/26
3.228.173.192/26
3.228.181.0/24
3.228.182.0/31
3.228.182.5/32
3.228.182.6/31
3.228.182.8/31
3.228.182.10/32
3.228.182.46/31
3.228.182.48/28
3.228.182.64/27
3.228.182.96/30
3.228.182.100/32
3.231.2.0/25
3.234.232.224/27
3.234.248.192/26
3.235.26.0/23
3.235.32.0/21
3.235.112.0/21
3.235.189.96/30
3.235.189.100/30
3.235.202.128/26
3.236.32.0/22
3.236.48.0/23
3.236.94.128/25
3.236.169.0/25
3.236.169.192/26
3.237.107.0/25
3.238.166.0/24
3.238.167.0/24
3.238.178.100/30
3.238.178.104/29
3.238.178.112/29
3.238.178.120/31
3.238.178.128/27
3.238.178.160/29
3.238.178.168/30
3.238.178.172/30
3.238.178.176/28
3.238.178.192/30
3.238.178.196/32
3.238.178.197/32
3.238.178.198/31
3.238.178.200/29
3.238.178.208/28
3.238.178.224/27
3.238.207.0/26
3.238.207.128/25
3.238.208.0/25
3.238.208.128/25
3.238.209.0/25
3.238.209.128/25
3.238.210.0/25
3.238.212.0/22
3.238.216.128/25
3.239.152.0/31
3.239.152.2/31
3.239.152.4/32
3.239.152.5/32
3.239.152.6/31
3.239.152.8/30
3.239.152.12/31
3.239.152.14/31
3.239.152.16/28
3.239.152.32/29
3.239.152.40/30
3.239.152.44/31
3.239.152.46/31
3.239.152.48/28
3.239.152.64/26
3.239.152.128/29
3.239.152.136/31
3.239.152.138/31
3.239.152.140/30
3.239.152.144/28
3.239.152.160/27
3.239.152.192/26
3.239.153.0/24
3.239.154.0/24
3.239.155.0/24
3.239.156.0/31
3.239.156.10/31
3.239.156.100/30
3.239.156.104/29
3.239.156.112/29
3.239.157.2/31
3.239.157.4/30
3.239.157.8/31
3.239.157.19/32
3.239.157.20/30
3.239.157.24/29
3.239.157.32/27
3.239.157.64/27
3.239.157.96/30
3.239.157.188/30
3.239.157.192/26
3.239.232.0/24
3.248.0.0/13
3.248.0.0/13
3.248.176.0/22
3.248.180.40/29
3.248.180.64/26
3.248.180.128/25
3.248.186.0/27
3.248.186.32/27
3.248.186.64/29
3.248.186.92/30
3.248.186.128/25
3.248.216.32/27
3.248.244.0/26
3.248.244.240/30
3.248.245.0/24
3.248.246.0/23
3.249.28.0/23
3.250.209.192/26
3.250.210.0/23
3.250.243.64/26
3.250.244.0/26
3.251.56.0/24
3.251.62.128/25
3.251.94.0/24
3.251.95.96/27
3.251.95.128/27
3.251.104.0/26
3.251.104.128/25
3.251.105.0/25
3.251.105.128/25
3.251.106.128/25
3.251.109.92/30
3.251.110.208/28
3.251.110.224/28
3.251.144.0/29
3.251.148.120/29
3.251.152.44/30
3.251.215.192/26
3.251.216.0/23
3.251.220.215/32
3.252.50.64/26
3.253.134.0/23
3.253.148.0/22
3.253.166.0/23
3.253.168.0/22
3.253.174.0/23
3.253.176.0/22
3.253.180.0/22
3.253.184.0/22
3.253.188.0/24
3.253.189.64/29
3.253.189.72/29
3.253.212.0/22
3.253.216.0/22
3.253.220.0/22
3.253.224.0/22
3.253.228.0/22
3.254.8.0/25
3.254.10.0/25
3.254.178.192/26
3.254.234.0/25
3.254.234.128/25
3.254.236.0/22
3.255.16.0/22
5.60.0.0/20
5.60.0.0/20
5.60.16.0/24
5.60.16.0/24
5.60.32.0/20
5.60.32.0/20
5.60.48.0/20
5.60.48.0/20
5.60.64.0/19
5.60.64.0/19
5.60.96.0/19
5.60.96.0/19
5.60.128.0/17
5.60.128.0/17
5.174.0.0/16
5.174.0.0/16
5.179.96.0/20
5.179.96.0/20
13.32.0.0/15
13.32.0.0/15
13.35.0.0/16
13.35.0.0/16
13.36.0.0/14
13.36.0.0/14
13.36.18.0/28
13.36.18.32/27
13.36.18.64/27
13.36.76.0/24
13.36.77.0/24
13.36.78.0/24
13.36.84.24/29
13.36.84.32/30
13.36.84.44/30
13.36.84.48/28
13.36.84.64/28
13.36.84.112/29
13.36.84.126/31
13.36.155.0/24
13.37.1.64/26
13.38.132.0/22
13.38.140.0/23
13.38.202.64/26
13.39.103.180/30
13.39.141.160/29
13.39.141.168/29
13.39.220.0/22
13.39.224.0/23
13.40.0.0/14
13.40.0.0/14
13.40.1.192/26
13.40.202.0/23
13.40.204.0/22
13.41.1.160/27
13.42.133.192/29
13.42.133.200/29
13.43.44.0/22
13.43.48.0/23
13.48.0.0/15
13.48.0.0/15
13.48.4.128/28
13.48.4.144/28
13.48.4.160/28
13.48.4.192/29
13.48.4.200/30
13.48.4.208/29
13.48.4.216/29
13.48.4.224/29
13.48.74.0/24
13.48.186.128/27
13.48.186.160/27
13.48.186.192/27
13.49.40.64/26
13.49.42.0/23
13.49.126.128/26
13.49.143.0/26
13.49.143.64/26

sudo: A terminal is required to authenticate

[
  {
    "cidr": "103.21.244.0/22",
    "ip_version": "IPv4",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "103.22.200.0/22",
    "ip_version": "IPv4",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "103.31.4.0/22",
    "ip_version": "IPv4",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "104.16.0.0/13",
    "ip_version": "IPv4",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "104.24.0.0/14",
    "ip_version": "IPv4",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "108.162.192.0/18",
    "ip_version": "IPv4",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "131.0.72.0/22",
    "ip_version": "IPv4",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "141.101.64.0/18",
    "ip_version": "IPv4",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "162.158.0.0/15",
    "ip_version": "IPv4",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "172.64.0.0/13",
    "ip_version": "IPv4",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "173.245.48.0/20",
    "ip_version": "IPv4",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "188.114.96.0/20",
    "ip_version": "IPv4",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "190.93.240.0/20",
    "ip_version": "IPv4",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "197.234.240.0/22",
    "ip_version": "IPv4",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "198.41.128.0/17",
    "ip_version": "IPv4",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "2400:cb00::/32",
    "ip_version": "IPv6",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "2405:8100::/32",
    "ip_version": "IPv6",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "2405:b500::/32",
    "ip_version": "IPv6",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "2606:4700::/32",
    "ip_version": "IPv6",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "2803:f800::/32",
    "ip_version": "IPv6",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "2a06:98c0::/29",
    "ip_version": "IPv6",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "2c0f:f248::/32",
    "ip_version": "IPv6",
    "provider": "cloudflare",
    "service": "",
    "region": "",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.1.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "us-west-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.1.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "us-west-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.4.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "us-east-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.4.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "us-east-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.4.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "us-east-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.5.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "us-east-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.5.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "us-east-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.5.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "us-east-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.6.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "us-east-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.6.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "us-east-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.6.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "us-east-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.7.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "eu-west-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.7.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "eu-west-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.7.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "eu-west-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.8.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "us-east-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.8.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "us-east-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.8.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "us-east-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.9.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "us-west-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.9.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "us-west-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.9.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "us-west-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.10.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "eu-central-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.10.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "eu-central-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.10.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "eu-central-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.11.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "ap-southeast-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.11.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "ap-southeast-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.11.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "ap-southeast-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.16.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "me-south-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.16.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "me-south-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.16.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "me-south-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.17.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "eu-south-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.17.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "eu-south-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.17.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "eu-south-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.18.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "af-south-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.18.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "af-south-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.18.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "af-south-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.19.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "ap-southeast-3",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.19.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "ap-southeast-3",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.19.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "ap-southeast-3",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.20.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "me-central-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.20.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "me-central-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.20.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "me-central-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.21.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "eu-central-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.21.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "eu-central-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.21.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "eu-central-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.22.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "eu-south-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.22.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "eu-south-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.22.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "eu-south-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.23.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "ap-south-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.23.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "ap-south-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.23.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "ap-south-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.24.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "ap-southeast-4",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.24.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "ap-southeast-4",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.24.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "ap-southeast-4",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.25.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "il-central-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.25.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "il-central-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.25.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "il-central-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.26.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "ca-west-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.26.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "ca-west-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.26.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "ca-west-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.27.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "ap-southeast-6",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.27.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "ap-southeast-6",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.27.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "ap-southeast-6",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.28.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "ap-southeast-7",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.28.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "ap-southeast-7",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.28.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "ap-southeast-7",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.29.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "mx-central-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.29.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "mx-central-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.29.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "mx-central-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.30.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "us-gov-west-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.30.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "us-gov-west-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.30.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "us-gov-west-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.31.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "ap-east-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.31.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "ap-east-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.31.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "ap-east-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.64.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "ap-northeast-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.64.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "ap-northeast-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.64.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "ap-northeast-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.65.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "us-west-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.65.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "us-west-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.65.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "us-west-2",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.72.0/21",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "GLOBAL",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.86.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "ap-southeast-3",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.86.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "ap-southeast-3",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.88.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "ap-south-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.88.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "ap-south-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.88.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "ap-south-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.89.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "AMAZON",
    "region": "ap-southeast-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.89.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "EC2",
    "region": "ap-southeast-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.89.0/24",
    "ip_version": "IPv4",
    "provider": "aws",
    "service": "S3",
    "region": "ap-southeast-1",
    "last_updated": "2026-10-24 02:30:05"
  },
  {
    "cidr": "1.178.90.0/24",
    "ip_version": "IPv4",
    "provider": "aws",

In [22]:
import hashlib, datetime, urllib.request
from pathlib import Path
import pandas as pd

RAW = Path("data/raw/lists") / datetime.date.today().isoformat()
RAW.mkdir(parents=True, exist_ok=True)

SOURCES = {
    "x4_vpn":        "https://raw.githubusercontent.com/X4BNet/lists_vpn/main/output/vpn/ipv4.txt",
    "x4_datacenter": "https://raw.githubusercontent.com/X4BNet/lists_vpn/main/output/datacenter/ipv4.txt",
    "cloud_merged":  "https://raw.githubusercontent.com/rezmoss/cloud-provider-ip-addresses/main/all_providers/all_providers_merged_v4.txt",
}

intervals, hashes = {}, {}
for name, url in SOURCES.items():
    data = urllib.request.urlopen(url, timeout=120).read()
    (RAW / f"{name}.txt").write_bytes(data)
    hashes[name] = hashlib.sha256(data).hexdigest()
    intervals[name] = load_intervals(RAW / f"{name}.txt")

# What's in each list
summary = pd.DataFrame({
    name: {"networks": len(s), "addresses": int((e - s + 1).sum())}
    for name, (s, e) in intervals.items()
}).T
summary["pct_of_ipv4"] = (summary["addresses"] / 2**32 * 100).round(2)
summary

# Check any IPs you like
def check(ips):
    ips = pd.Series(list(ips), name="ip")
    out = pd.DataFrame({"ip": ips})
    for name, (s, e) in intervals.items():
        out[name] = flag_ips(ips, s, e)
    out["checkable"] = ips.map(ip_to_u32) >= 0
    return out

check(["52.95.110.1", "8.8.8.8", "81.2.69.142", "2001:db8::1"])

            ip  x4_vpn  x4_datacenter  cloud_merged  checkable
0  52.95.110.1   False           True          True       True
1      8.8.8.8   False           True          True       True
2  81.2.69.142   False          False         False       True
3  2001:db8::1   False          False         False      False

In [ ]:
import pandas as pd
caida = pd.read_csv(
    "../data/IP/routeviews-rv6-20261023-0200.pfx2as.gz",
    sep="\t",
    header=None,
    # names=["range_start", "range_end", "asn", "country_code", "description"],
    keep_default_na=False,
)

caida.head(10)

                 0   1       2
0    2000:b70:25::  48  262191
1           2001::  32    6939
2     2001:4:112::  48     112
3       2001:200::  32    2500
4   2001:200:600::  40    7667
5   2001:200:900::  40    7660
6   2001:200:e00::  40    4690
7  2001:200:c000::  35   23634
8  2001:200:e000::  35    7660
9       2001:218::  32    2914

In [23]:
import hashlib, datetime, urllib.request
from pathlib import Path
import pandas as pd

RAW = Path("data/raw/lists") / datetime.date.today().isoformat()
RAW.mkdir(parents=True, exist_ok=True)

URL = ("https://raw.githubusercontent.com/rezmoss/cloud-provider-ip-addresses/"
       "main/all_providers/all_providers.json")
path = RAW / "rezmoss_all_providers.json"

data = urllib.request.urlopen(URL, timeout=300).read()   # ~91 MB
path.write_bytes(data)
hashes["rezmoss_all_providers"] = hashlib.sha256(data).hexdigest()  # or a new dict if `hashes` doesn't exist yet

providers = pd.read_json(path)
providers.head()

              cidr ip_version    provider service region         last_updated
0  103.21.244.0/22       IPv4  cloudflare                 2026-10-24 02:30:05
1  103.22.200.0/22       IPv4  cloudflare                 2026-10-24 02:30:05
2    103.31.4.0/22       IPv4  cloudflare                 2026-10-24 02:30:05
3    104.16.0.0/13       IPv4  cloudflare                 2026-10-24 02:30:05
4    104.24.0.0/14       IPv4  cloudflare                 2026-10-24 02:30:05

In [24]:
BAD_ASN_URL = "https://raw.githubusercontent.com/brianhama/bad-asn-list/master/bad-asn-list.csv"
p = RAW / "bad_asn_list.csv"
data = urllib.request.urlopen(BAD_ASN_URL, timeout=60).read()
p.write_bytes(data)
hashes["bad_asn_list"] = hashlib.sha256(data).hexdigest()

bad_asn = pd.read_csv(p).drop_duplicates("ASN")
bad_asn_set = set(bad_asn["ASN"])
len(bad_asn)

723

## Publication audit: 24 October 2026

This standalone audit records the exact hashes, coverage, overlap, provider-row, and bad-ASN measurements cited by the site page. The raw bytes were downloaded again on the date above by `ip_enrichment_snapshot.py`.

In [25]:
import hashlib
import json
from pathlib import Path

from ip_enrichment_snapshot import profile_snapshot

SNAPSHOT = Path("data/raw/lists/2026-10-24")
artifact_paths = {
    "x4_vpn": SNAPSHOT / "x4_vpn.txt",
    "x4_datacenter": SNAPSHOT / "x4_datacenter.txt",
    "rezmoss_merged_v4": SNAPSHOT / "rezmoss_merged_v4.txt",
    "rezmoss_all_providers": SNAPSHOT / "rezmoss_all_providers.json",
    "bad_asn_list": SNAPSHOT / "bad_asn_list.csv",
    "tor_bulk_exit_list": SNAPSHOT / "tor_bulk_exit_list.txt",
}
audit = {
    "sha256": {
        name: hashlib.sha256(path.read_bytes()).hexdigest()
        for name, path in artifact_paths.items()
    },
    "profile": profile_snapshot(SNAPSHOT),
}
print(json.dumps(audit, indent=2))

{
  "sha256": {
    "x4_vpn": "d5555f06a151141d08d79bbbcb96150f979860b48d8bfd66515ffa4d3fcc4ef7",
    "x4_datacenter": "380eccc1e05d05b3535dff6c380a0fb9d8bd6978018c972599cbb50c13389202",
    "rezmoss_merged_v4": "115a926058b183792e538e92cb369b7403333ab0952f1898d44507ef7ebba2f2",
    "rezmoss_all_providers": "38515c1f594536a47e44823d8926f371deb8cf094e17cde17710ce16648f93ea",
    "bad_asn_list": "0af8e58dc07ba070a10c9083a1a9f5c9fc76be35fab32bb6d144e72caa20a252",
    "tor_bulk_exit_list": "e5e35bc551f1e52ae89b9182eab5a73c878750a39d3bd497a065ee97cfced506"
  },
  "profile": {
    "coverage": [
      {
        "list": "x4_vpn",
        "networks": 10931,
        "addresses": 3170072,
        "pct_of_ipv4": 0.07380899041891098
      },
      {
        "list": "x4_datacenter",
        "networks": 44584,
        "addresses": 395597872,
        "pct_of_ipv4": 9.210730716586113
      },
      {
        "list": "rezmoss_merged_v4",
        "networks": 12840,
        "addresses": 255279192,
        "pct_of_ipv4": 5.943681858479977
      }
    ],
    "overlap": {
      "rezmoss_addresses_in_x4_datacenter": 234192021,
      "rezmoss_pct_in_x4_datacenter": 91.73956528348774,
      "vpn_addresses_in_x4_datacenter": 3145854,
      "vpn_pct_in_x4_datacenter": 99.23604258830714,
      "vpn_network_starts_in_x4_datacenter": 8249,
      "vpn_networks_fully_in_x4_datacenter": 8242
    },
    "x4_datacenter_expanded_text_bytes": 5546312566,
    "rezmoss_rows": {
      "total": 466408,
      "ipv4": 167064,
      "ipv6": 299344,
      "ipv6_pct": 64.18071731188144
    },
    "bad_asn": {
      "rows": 742,
      "unique_asns": 723,
      "rows_16_bit": 641,
      "unique_16_bit": 623,
      "maximum_asn": 398779
    },
    "tor_bulk_exit_list": {
      "distinct_addresses": 1210
    }
  }
}